# Generated by Django 5.2.8 on 2025-11-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
                ('fechafin', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='tipoelemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipoelemento',
                'verbose_name_plural': 'tipoelementos',
                'db_table': 'tipoelemento',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidadmedida',
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
                ('telefono', models.TextField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('direccion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
                ('especialidad', models.TextField()),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
                ('codigo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estadoMatricula', models.TextField(blank=True, max_length=20, null=True, verbose_name='Estado de Matricula')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stockActual', models.IntegerField()),
                ('stockMinimo', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('tipoElementoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoelemento')),
                ('unidadMedidaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidadmedida')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'db_table': 'elemento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('elementoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.elemento')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimiento',
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('creador_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Evento',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docenteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.docente'),
        ),
        migrations.CreateModel(
            name='Estudianteacudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acudienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acudiente')),
                ('estudianteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
            options={
                'verbose_name': 'Estudianteacudiente',
                'verbose_name_plural': 'Estudianteacudientes',
                'db_table': 'Estudianteacudiente',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('horaentrada', models.TimeField()),
                ('horasalida', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('odsevaciones', models.TextField()),
                ('estudianteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'db_table': 'asistencia',
            },
        ),
    ]
